package com.tumblr.albandaci.learntoreadthequran.Surahs;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.widget.Toast;

import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.AdView;
import com.tumblr.albandaci.learntoreadthequran.Adapter.Al_Fatihah_Adapter;
import com.tumblr.albandaci.learntoreadthequran.R;

public class As_Saffat extends AppCompatActivity {

    private RecyclerView recyclerView;
    private RecyclerView.Adapter adapter;
    private RecyclerView.LayoutManager layoutManager;

    String [] verses = {"37:1", "37:2", "37:3", "37:4", "37:5", "37:6", "37:7", "37:8", "37:9", "37:10", "37:11", "37:12", "37:13", "37:14", "37:15", "37:16",
            "37:17", "37:18", "37:19", "37:20", "37:21", "37:22", "37:23", "37:24", "37:25", "37:26", "37:27", "37:28", "37:29", "37:30", "37:31", "37:32",
            "37:33", "37:34", "37:35", "37:36", "37:37", "37:38", "37:39", "37:40", "37:41", "37:42", "37:43", "37:44", "37:45", "37:46", "37:47", "37:48",
            "37:49", "37:50", "37:51", "37:52", "37:53", "37:54", "37:55", "37:56", "37:57", "37:58", "37:59", "37:60", "37:61", "37:62", "37:63", "37:64",
            "37:65", "37:66", "37:67", "37:68", "37:69", "37:70", "37:71", "37:72", "37:73", "37:74", "37:75", "37:76", "37:77", "37:78", "37:79", "37:80",
            "37:81", "37:82", "37:83", "37:84", "37:85", "37:86", "37:87", "37:88", "37:89", "37:90", "37:91", "37:92", "37:93", "37:94", "37:95", "37:96",
            "37:97", "37:98", "37:99", "37:100", "37:101", "37:102", "37:103", "37:104", "37:105", "37:106", "37:107", "37:108", "37:109", "37:110", "37:111", "37:112",
            "37:113", "37:114", "37:115", "37:116", "37:117", "37:118", "37:119", "37:120", "37:121", "37:122", "37:123", "37:124", "37:125", "37:126", "37:127", "37:128",
            "37:129", "37:130", "37:131", "37:132", "37:133", "37:134", "37:135", "37:136", "37:137", "37:138", "37:139", "37:140", "37:141", "37:142", "37:143", "37:144",
            "37:145", "37:146", "37:147", "37:148", "37:149", "37:150", "37:151", "37:152", "37:153", "37:154", "37:155", "37:156", "37:157", "37:158", "37:159", "37:160",
            "37:161", "37:162", "37:163", "37:164", "37:165", "37:166", "37:167", "37:168", "37:169", "37:170", "37:171", "37:172", "37:173", "37:174", "37:175", "37:176",
            "37:177", "37:178", "37:179", "37:180", "37:181", "37:182", ""};

    String [] arabic_verses = {"وَالصَّافَّاتِ صَفًّا",
    "فَالزَّاجِرَاتِ زَجْرًا",
    "فَالتَّالِيَاتِ ذِكْرًا",
    "إِنَّ إِلَٰهَكُمْ لَوَاحِدٌ",
    "رَّبُّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا وَرَبُّ الْمَشَارِقِ",
    "إِنَّا زَيَّنَّا السَّمَاءَ الدُّنْيَا بِزِينَةٍ الْكَوَاكِبِ",
    "وَحِفْظًا مِّن كُلِّ شَيْطَانٍ مَّارِدٍ",
    "لَّا يَسَّمَّعُونَ إِلَى الْمَلَإِ الْأَعْلَىٰ وَيُقْذَفُونَ مِن كُلِّ جَانِبٍ",
    "دُحُورًا ۖ وَلَهُمْ عَذَابٌ وَاصِبٌ",
    "إِلَّا مَنْ خَطِفَ الْخَطْفَةَ فَأَتْبَعَهُ شِهَابٌ ثَاقِبٌ",
    "فَاسْتَفْتِهِمْ أَهُمْ أَشَدُّ خَلْقًا أَم مَّنْ خَلَقْنَا ۚ إِنَّا خَلَقْنَاهُم مِّن طِينٍ لَّازِبٍ",
    "بَلْ عَجِبْتَ وَيَسْخَرُونَ",
    "وَإِذَا ذُكِّرُوا لَا يَذْكُرُونَ",
    "وَإِذَا رَأَوْا آيَةً يَسْتَسْخِرُونَ",
    "وَقَالُوا إِنْ هَٰذَا إِلَّا سِحْرٌ مُّبِينٌ",
    "أَإِذَا مِتْنَا وَكُنَّا تُرَابًا وَعِظَامًا أَإِنَّا لَمَبْعُوثُونَ",
    "أَوَآبَاؤُنَا الْأَوَّلُونَ",
    "قُلْ نَعَمْ وَأَنتُمْ دَاخِرُونَ",
    "فَإِنَّمَا هِيَ زَجْرَةٌ وَاحِدَةٌ فَإِذَا هُمْ يَنظُرُونَ",
    "وَقَالُوا يَا وَيْلَنَا هَٰذَا يَوْمُ الدِّينِ",
    "هَٰذَا يَوْمُ الْفَصْلِ الَّذِي كُنتُم بِهِ تُكَذِّبُونَ",
    "احْشُرُوا الَّذِينَ ظَلَمُوا وَأَزْوَاجَهُمْ وَمَا كَانُوا يَعْبُدُونَ",
    "مِن دُونِ اللَّهِ فَاهْدُوهُمْ إِلَىٰ صِرَاطِ الْجَحِيمِ",
    "وَقِفُوهُمْ ۖ إِنَّهُم مَّسْئُولُونَ",
    "مَا لَكُمْ لَا تَنَاصَرُونَ",
    "بَلْ هُمُ الْيَوْمَ مُسْتَسْلِمُونَ",
    "وَأَقْبَلَ بَعْضُهُمْ عَلَىٰ بَعْضٍ يَتَسَاءَلُونَ",
    "قَالُوا إِنَّكُمْ كُنتُمْ تَأْتُونَنَا عَنِ الْيَمِينِ",
    "قَالُوا بَل لَّمْ تَكُونُوا مُؤْمِنِينَ",
    "وَمَا كَانَ لَنَا عَلَيْكُم مِّن سُلْطَانٍ ۖ بَلْ كُنتُمْ قَوْمًا طَاغِينَ",
    "فَحَقَّ عَلَيْنَا قَوْلُ رَبِّنَا ۖ إِنَّا لَذَائِقُونَ",
    "فَأَغْوَيْنَاكُمْ إِنَّا كُنَّا غَاوِينَ",
    "فَإِنَّهُمْ يَوْمَئِذٍ فِي الْعَذَابِ مُشْتَرِكُونَ",
    "إِنَّا كَذَٰلِكَ نَفْعَلُ بِالْمُجْرِمِينَ",
    "إِنَّهُمْ كَانُوا إِذَا قِيلَ لَهُمْ لَا إِلَٰهَ إِلَّا اللَّهُ يَسْتَكْبِرُونَ",
    "وَيَقُولُونَ أَئِنَّا لَتَارِكُو آلِهَتِنَا لِشَاعِرٍ مَّجْنُونٍ",
    "بَلْ جَاءَ بِالْحَقِّ وَصَدَّقَ الْمُرْسَلِينَ",
    "إِنَّكُمْ لَذَائِقُو الْعَذَابِ الْأَلِيمِ",
    "وَمَا تُجْزَوْنَ إِلَّا مَا كُنتُمْ تَعْمَلُونَ",
    "إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ",
    "أُولَٰئِكَ لَهُمْ رِزْقٌ مَّعْلُومٌ",
    "فَوَاكِهُ ۖ وَهُم مُّكْرَمُونَ",
    "فِي جَنَّاتِ النَّعِيمِ",
    "عَلَىٰ سُرُرٍ مُّتَقَابِلِينَ",
    "يُطَافُ عَلَيْهِم بِكَأْسٍ مِّن مَّعِينٍ",
    "بَيْضَاءَ لَذَّةٍ لِّلشَّارِبِينَ",
    "لَا فِيهَا غَوْلٌ وَلَا هُمْ عَنْهَا يُنزَفُونَ",
    "وَعِندَهُمْ قَاصِرَاتُ الطَّرْفِ عِينٌ",
    "كَأَنَّهُنَّ بَيْضٌ مَّكْنُونٌ",
    "فَأَقْبَلَ بَعْضُهُمْ عَلَىٰ بَعْضٍ يَتَسَاءَلُونَ",
    "قَالَ قَائِلٌ مِّنْهُمْ إِنِّي كَانَ لِي قَرِينٌ",
    "يَقُولُ أَإِنَّكَ لَمِنَ الْمُصَدِّقِينَ",
    "أَإِذَا مِتْنَا وَكُنَّا تُرَابًا وَعِظَامًا أَإِنَّا لَمَدِينُونَ",
    "قَالَ هَلْ أَنتُم مُّطَّلِعُونَ",
    "فَاطَّلَعَ فَرَآهُ فِي سَوَاءِ الْجَحِيمِ",
    "قَالَ تَاللَّهِ إِن كِدتَّ لَتُرْدِينِ",
    "وَلَوْلَا نِعْمَةُ رَبِّي لَكُنتُ مِنَ الْمُحْضَرِينَ",
    "أَفَمَا نَحْنُ بِمَيِّتِينَ",
    "إِلَّا مَوْتَتَنَا الْأُولَىٰ وَمَا نَحْنُ بِمُعَذَّبِينَ",
    "إِنَّ هَٰذَا لَهُوَ الْفَوْزُ الْعَظِيمُ",
    "لِمِثْلِ هَٰذَا فَلْيَعْمَلِ الْعَامِلُونَ",
    "أَذَٰلِكَ خَيْرٌ نُّزُلًا أَمْ شَجَرَةُ الزَّقُّومِ",
    "إِنَّا جَعَلْنَاهَا فِتْنَةً لِّلظَّالِمِينَ",
    "إِنَّهَا شَجَرَةٌ تَخْرُجُ فِي أَصْلِ الْجَحِيمِ",
    "طَلْعُهَا كَأَنَّهُ رُءُوسُ الشَّيَاطِينِ",
    "فَإِنَّهُمْ لَآكِلُونَ مِنْهَا فَمَالِئُونَ مِنْهَا الْبُطُونَ",
    "ثُمَّ إِنَّ لَهُمْ عَلَيْهَا لَشَوْبًا مِّنْ حَمِيمٍ",
    "ثُمَّ إِنَّ مَرْجِعَهُمْ لَإِلَى الْجَحِيمِ",
    "إِنَّهُمْ أَلْفَوْا آبَاءَهُمْ ضَالِّينَ",
    "فَهُمْ عَلَىٰ آثَارِهِمْ يُهْرَعُونَ",
    "وَلَقَدْ ضَلَّ قَبْلَهُمْ أَكْثَرُ الْأَوَّلِينَ",
    "وَلَقَدْ أَرْسَلْنَا فِيهِم مُّنذِرِينَ",
    "فَانظُرْ كَيْفَ كَانَ عَاقِبَةُ الْمُنذَرِينَ",
    "إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ",
    "وَلَقَدْ نَادَانَا نُوحٌ فَلَنِعْمَ الْمُجِيبُونَ",
    "وَنَجَّيْنَاهُ وَأَهْلَهُ مِنَ الْكَرْبِ الْعَظِيمِ",
    "وَجَعَلْنَا ذُرِّيَّتَهُ هُمُ الْبَاقِينَ",
    "وَتَرَكْنَا عَلَيْهِ فِي الْآخِرِينَ",
    "سَلَامٌ عَلَىٰ نُوحٍ فِي الْعَالَمِينَ",
    "إِنَّا كَذَٰلِكَ نَجْزِي الْمُحْسِنِينَ",
    "إِنَّهُ مِنْ عِبَادِنَا الْمُؤْمِنِينَ",
    "ثُمَّ أَغْرَقْنَا الْآخَرِينَ",
    "وَإِنَّ مِن شِيعَتِهِ لَإِبْرَاهِيمَ",
    "إِذْ جَاءَ رَبَّهُ بِقَلْبٍ سَلِيمٍ",
    "إِذْ قَالَ لِأَبِيهِ وَقَوْمِهِ مَاذَا تَعْبُدُونَ",
    "أَئِفْكًا آلِهَةً دُونَ اللَّهِ تُرِيدُونَ",
    "فَمَا ظَنُّكُم بِرَبِّ الْعَالَمِينَ",
    "فَنَظَرَ نَظْرَةً فِي النُّجُومِ",
    "فَقَالَ إِنِّي سَقِيمٌ",
    "فَتَوَلَّوْا عَنْهُ مُدْبِرِينَ",
    "فَرَاغَ إِلَىٰ آلِهَتِهِمْ فَقَالَ أَلَا تَأْكُلُونَ",
    "مَا لَكُمْ لَا تَنطِقُونَ",
    "فَرَاغَ عَلَيْهِمْ ضَرْبًا بِالْيَمِينِ",
    "فَأَقْبَلُوا إِلَيْهِ يَزِفُّونَ",
    "قَالَ أَتَعْبُدُونَ مَا تَنْحِتُونَ",
    "وَاللَّهُ خَلَقَكُمْ وَمَا تَعْمَلُونَ",
    "قَالُوا ابْنُوا لَهُ بُنْيَانًا فَأَلْقُوهُ فِي الْجَحِيمِ",
    "فَأَرَادُوا بِهِ كَيْدًا فَجَعَلْنَاهُمُ الْأَسْفَلِينَ",
    "وَقَالَ إِنِّي ذَاهِبٌ إِلَىٰ رَبِّي سَيَهْدِينِ",
    "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
    "فَبَشَّرْنَاهُ بِغُلَامٍ حَلِيمٍ",
    "فَلَمَّا بَلَغَ مَعَهُ السَّعْيَ قَالَ يَا بُنَيَّ إِنِّي أَرَىٰ فِي الْمَنَامِ أَنِّي أَذْبَحُكَ فَانظُرْ مَاذَا تَرَىٰ ۚ قَالَ يَا أَبَتِ افْعَلْ مَا تُؤْمَرُ ۖ سَتَجِدُنِي إِن شَاءَ اللَّهُ مِنَ الصَّابِرِينَ",
    "فَلَمَّا أَسْلَمَا وَتَلَّهُ لِلْجَبِينِ",
    "وَنَادَيْنَاهُ أَن يَا إِبْرَاهِيمُ",
    "قَدْ صَدَّقْتَ الرُّؤْيَا ۚ إِنَّا كَذَٰلِكَ نَجْزِي الْمُحْسِنِينَ",
    "إِنَّ هَٰذَا لَهُوَ الْبَلَاءُ الْمُبِينُ",
    "وَفَدَيْنَاهُ بِذِبْحٍ عَظِيمٍ",
    "وَتَرَكْنَا عَلَيْهِ فِي الْآخِرِينَ",
    "سَلَامٌ عَلَىٰ إِبْرَاهِيمَ",
    "كَذَٰلِكَ نَجْزِي الْمُحْسِنِينَ",
    "إِنَّهُ مِنْ عِبَادِنَا الْمُؤْمِنِينَ",
    "وَبَشَّرْنَاهُ بِإِسْحَاقَ نَبِيًّا مِّنَ الصَّالِحِينَ",
    "وَبَارَكْنَا عَلَيْهِ وَعَلَىٰ إِسْحَاقَ ۚ وَمِن ذُرِّيَّتِهِمَا مُحْسِنٌ وَظَالِمٌ لِّنَفْسِهِ مُبِينٌ",
    "وَلَقَدْ مَنَنَّا عَلَىٰ مُوسَىٰ وَهَارُونَ",
    "وَنَجَّيْنَاهُمَا وَقَوْمَهُمَا مِنَ الْكَرْبِ الْعَظِيمِ",
    "وَنَصَرْنَاهُمْ فَكَانُوا هُمُ الْغَالِبِينَ",
    "وَآتَيْنَاهُمَا الْكِتَابَ الْمُسْتَبِينَ",
    "وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ",
    "وَتَرَكْنَا عَلَيْهِمَا فِي الْآخِرِينَ",
    "سَلَامٌ عَلَىٰ مُوسَىٰ وَهَارُونَ",
    "إِنَّا كَذَٰلِكَ نَجْزِي الْمُحْسِنِينَ",
    "إِنَّهُمَا مِنْ عِبَادِنَا الْمُؤْمِنِينَ",
    "وَإِنَّ إِلْيَاسَ لَمِنَ الْمُرْسَلِينَ",
    "إِذْ قَالَ لِقَوْمِهِ أَلَا تَتَّقُونَ",
    "أَتَدْعُونَ بَعْلًا وَتَذَرُونَ أَحْسَنَ الْخَالِقِينَ",
    "اللَّهَ رَبَّكُمْ وَرَبَّ آبَائِكُمُ الْأَوَّلِينَ",
    "فَكَذَّبُوهُ فَإِنَّهُمْ لَمُحْضَرُونَ",
    "إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ",
    "وَتَرَكْنَا عَلَيْهِ فِي الْآخِرِينَ",
    "سَلَامٌ عَلَىٰ إِلْ يَاسِينَ",
    "إِنَّا كَذَٰلِكَ نَجْزِي الْمُحْسِنِينَ",
    "إِنَّهُ مِنْ عِبَادِنَا الْمُؤْمِنِينَ",
    "وَإِنَّ لُوطًا لَّمِنَ الْمُرْسَلِينَ",
    "إِذْ نَجَّيْنَاهُ وَأَهْلَهُ أَجْمَعِينَ",
    "إِلَّا عَجُوزًا فِي الْغَابِرِينَ",
    "ثُمَّ دَمَّرْنَا الْآخَرِينَ",
    "وَإِنَّكُمْ لَتَمُرُّونَ عَلَيْهِم مُّصْبِحِينَ",
    "وَبِاللَّيْلِ ۗ أَفَلَا تَعْقِلُونَ",
    "وَإِنَّ يُونُسَ لَمِنَ الْمُرْسَلِينَ",
    "إِذْ أَبَقَ إِلَى الْفُلْكِ الْمَشْحُونِ",
    "فَسَاهَمَ فَكَانَ مِنَ الْمُدْحَضِينَ",
    "فَالْتَقَمَهُ الْحُوتُ وَهُوَ مُلِيمٌ",
    "فَلَوْلَا أَنَّهُ كَانَ مِنَ الْمُسَبِّحِينَ",
    "لَلَبِثَ فِي بَطْنِهِ إِلَىٰ يَوْمِ يُبْعَثُونَ",
    "فَنَبَذْنَاهُ بِالْعَرَاءِ وَهُوَ سَقِيمٌ",
    "وَأَنبَتْنَا عَلَيْهِ شَجَرَةً مِّن يَقْطِينٍ",
    "وَأَرْسَلْنَاهُ إِلَىٰ مِائَةِ أَلْفٍ أَوْ يَزِيدُونَ",
    "فَآمَنُوا فَمَتَّعْنَاهُمْ إِلَىٰ حِينٍ",
    "فَاسْتَفْتِهِمْ أَلِرَبِّكَ الْبَنَاتُ وَلَهُمُ الْبَنُونَ",
    "أَمْ خَلَقْنَا الْمَلَائِكَةَ إِنَاثًا وَهُمْ شَاهِدُونَ",
    "أَلَا إِنَّهُم مِّنْ إِفْكِهِمْ لَيَقُولُونَ",
    "وَلَدَ اللَّهُ وَإِنَّهُمْ لَكَاذِبُونَ",
    "أَصْطَفَى الْبَنَاتِ عَلَى الْبَنِينَ",
    "مَا لَكُمْ كَيْفَ تَحْكُمُونَ",
    "أَفَلَا تَذَكَّرُونَ",
    "أَمْ لَكُمْ سُلْطَانٌ مُّبِينٌ",
    "فَأْتُوا بِكِتَابِكُمْ إِن كُنتُمْ صَادِقِينَ",
    "وَجَعَلُوا بَيْنَهُ وَبَيْنَ الْجِنَّةِ نَسَبًا ۚ وَلَقَدْ عَلِمَتِ الْجِنَّةُ إِنَّهُمْ لَمُحْضَرُونَ",
    "سُبْحَانَ اللَّهِ عَمَّا يَصِفُونَ",
    "إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ",
    "فَإِنَّكُمْ وَمَا تَعْبُدُونَ",
    "مَا أَنتُمْ عَلَيْهِ بِفَاتِنِينَ",
    "إِلَّا مَنْ هُوَ صَالِ الْجَحِيمِ",
    "وَمَا مِنَّا إِلَّا لَهُ مَقَامٌ مَّعْلُومٌ",
    "وَإِنَّا لَنَحْنُ الصَّافُّونَ",
    "وَإِنَّا لَنَحْنُ الْمُسَبِّحُونَ",
    "وَإِن كَانُوا لَيَقُولُونَ",
    "لَوْ أَنَّ عِندَنَا ذِكْرًا مِّنَ الْأَوَّلِينَ",
    "لَكُنَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ",
    "فَكَفَرُوا بِهِ ۖ فَسَوْفَ يَعْلَمُونَ",
    "وَلَقَدْ سَبَقَتْ كَلِمَتُنَا لِعِبَادِنَا الْمُرْسَلِينَ",
    "إِنَّهُمْ لَهُمُ الْمَنصُورُونَ",
    "وَإِنَّ جُندَنَا لَهُمُ الْغَالِبُونَ",
    "فَتَوَلَّ عَنْهُمْ حَتَّىٰ حِينٍ",
    "وَأَبْصِرْهُمْ فَسَوْفَ يُبْصِرُونَ",
    "أَفَبِعَذَابِنَا يَسْتَعْجِلُونَ",
    "فَإِذَا نَزَلَ بِسَاحَتِهِمْ فَسَاءَ صَبَاحُ الْمُنذَرِينَ",
    "وَتَوَلَّ عَنْهُمْ حَتَّىٰ حِينٍ",
    "وَأَبْصِرْ فَسَوْفَ يُبْصِرُونَ",
    "سُبْحَانَ رَبِّكَ رَبِّ الْعِزَّةِ عَمَّا يَصِفُونَ",
    "وَسَلَامٌ عَلَى الْمُرْسَلِينَ",
    "وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    ""};

    String [] sahih_international = {"Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", ""};

    String [] english_verses = {"By those [angels] lined up in rows",
    "And those who drive [the clouds]",
    "And those who recite the message,",
    "Indeed, your God is One,",
    "Lord of the heavens and the earth and that between them and Lord of the sunrises.",
    "Indeed, We have adorned the nearest heaven with an adornment of stars",
    "And as protection against every rebellious devil",
    "[So] they may not listen to the exalted assembly [of angels] and are pelted from every side,",
    "Repelled; and for them is a constant punishment,",
    "Except one who snatches [some words] by theft, but they are pursued by a burning flame, piercing [in brightness].",
    "Then inquire of them, [O Muhammad], \"Are they a stronger [or more difficult] creation or those [others] We have created?\" Indeed, We created men from sticky clay.",
    "But you wonder, while they mock,",
    "And when they are reminded, they remember not.",
    "And when they see a sign, they ridicule",
    "And say, \"This is not but obvious magic.",
    "When we have died and become dust and bones, are we indeed to be resurrected?",
    "And our forefathers [as well]?\"",
    "Say, \"Yes, and you will be [rendered] contemptible.\"",
    "It will be only one shout, and at once they will be observing.",
    "They will say, \"O woe to us! This is the Day of Recompense.\"",
    "[They will be told], \"This is the Day of Judgement which you used to deny.\"",
    "[The angels will be ordered], \"Gather those who committed wrong, their kinds, and what they used to worship",
    "Other than Allah, and guide them to the path of Hellfire",
    "And stop them; indeed, they are to be questioned.\"",
    "[They will be asked], \"What is [wrong] with you? Why do you not help each other?\"",
    "But they, that Day, are in surrender.",
    "And they will approach one another blaming each other.",
    "They will say, \"Indeed, you used to come at us from the right.\"",
    "The oppressors will say, \"Rather, you [yourselves] were not believers,",
    "And we had over you no authority, but you were a transgressing people.",
    "So the word of our Lord has come into effect upon us; indeed, we will taste [punishment].",
    "And we led you to deviation; indeed, we were deviators.\"",
    "So indeed they, that Day, will be sharing in the punishment.",
    "Indeed, that is how We deal with the criminals.",
    "Indeed they, when it was said to them, \"There is no deity but Allah,\" were arrogant",
    "And were saying, \"Are we to leave our gods for a mad poet?\"",
    "Rather, the Prophet has come with the truth and confirmed the [previous] messengers.",
    "Indeed, you [disbelievers] will be tasters of the painful punishment,",
    "And you will not be recompensed except for what you used to do -",
    "But not the chosen servants of Allah.",
    "Those will have a provision determined -",
    "Fruits; and they will be honored",
    "In gardens of pleasure",
    "On thrones facing one another.",
    "There will be circulated among them a cup [of wine] from a flowing spring,",
    "White and delicious to the drinkers;",
    "No bad effect is there in it, nor from it will they be intoxicated.",
    "And with them will be women limiting [their] glances, with large, [beautiful] eyes,",
    "As if they were [delicate] eggs, well-protected.",
    "And they will approach one another, inquiring of each other.",
    "A speaker among them will say, \"Indeed, I had a companion [on earth]",
    "Who would say, 'Are you indeed of those who believe",
    "That when we have died and become dust and bones, we will indeed be recompensed?'\"",
    "He will say, \"Would you [care to] look?\"",
    "And he will look and see him in the midst of the Hellfire.",
    "He will say, \"By Allah, you almost ruined me.",
    "If not for the favor of my Lord, I would have been of those brought in [to Hell].",
    "Then, are we not to die",
    "Except for our first death, and we will not be punished?\"",
    "Indeed, this is the great attainment.",
    "For the like of this let the workers [on earth] work.",
    "Is Paradise a better accommodation or the tree of zaqqum?",
    "Indeed, We have made it a torment for the wrongdoers.",
    "Indeed, it is a tree issuing from the bottom of the Hellfire,",
    "Its emerging fruit as if it was heads of the devils.",
    "And indeed, they will eat from it and fill with it their bellies.",
    "Then indeed, they will have after it a mixture of scalding water.",
    "Then indeed, their return will be to the Hellfire.",
    "Indeed they found their fathers astray.",
    "So they hastened [to follow] in their footsteps.",
    "And there had already strayed before them most of the former peoples,",
    "And We had already sent among them warners.",
    "Then look how was the end of those who were warned -",
    "But not the chosen servants of Allah.",
    "And Noah had certainly called Us, and [We are] the best of responders.",
    "And We saved him and his family from the great affliction.",
    "And We made his descendants those remaining [on the earth]",
    "And left for him [favorable mention] among later generations:",
    "\"Peace upon Noah among the worlds.\"",
    "Indeed, We thus reward the doers of good.",
    "Indeed, he was of Our believing servants.",
    "Then we drowned the others [i.e., disbelievers]",
    "And indeed, among his kind was Abraham,",
    "When he came to his Lord with a sound heart",
    "[And] when he said to his father and his people, \"What do you worship?",
    "Is it falsehood [as] gods other than Allah you desire?",
    "Then what is your thought about the Lord of the worlds?\"",
    "And he cast a look at the stars",
    "And said, \"Indeed, I am [about to be] ill.\"",
    "So they turned away from him, departing.",
    "Then he turned to their gods and said, \"Do you not eat?",
    "What is [wrong] with you that you do not speak?\"",
    "And he turned upon them a blow with [his] right hand.",
    "Then the people came toward him, hastening.",
    "He said, \"Do you worship that which you [yourselves] carve,",
    "While Allah created you and that which you do?\"",
    "They said, \"Construct for him a furnace and throw him into the burning fire.\"",
    "And they intended for him a plan, but We made them the most debased.",
    "And [then] he said, \"Indeed, I will go to [where I am ordered by] my Lord; He will guide me.",
    "My Lord, grant me [a child] from among the righteous.\"",
    "So We gave him good tidings of a forbearing boy.",
    "And when he reached with him [the age of] exertion, he said, \"O my son, indeed I have seen in a dream that I [must] sacrifice you, so see what you think.\" He said, \"O my father, do as you are commanded. You will find me, if Allah wills, of the steadfast.\"",
    "And when they had both submitted and he put him down upon his forehead,",
    "We called to him, \"O Abraham,",
    "You have fulfilled the vision.\" Indeed, We thus reward the doers of good.",
    "Indeed, this was the clear trial.",
    "And We ransomed him with a great sacrifice,",
    "And We left for him [favorable mention] among later generations:",
    "\"Peace upon Abraham.\"",
    "Indeed, We thus reward the doers of good.",
    "Indeed, he was of Our believing servants.",
    "And We gave him good tidings of Isaac, a prophet from among the righteous.",
    "And We blessed him and Isaac. But among their descendants is the doer of good and the clearly unjust to himself.",
    "And We did certainly confer favor upon Moses and Aaron.",
    "And We saved them and their people from the great affliction,",
    "And We supported them so it was they who overcame.",
    "And We gave them the explicit Scripture,",
    "And We guided them on the straight path.",
    "And We left for them [favorable mention] among later generations:",
    "\"Peace upon Moses and Aaron.\"",
    "Indeed, We thus reward the doers of good.",
    "Indeed, they were of Our believing servants.",
    "And indeed, Elias was from among the messengers,",
    "When he said to his people, \"Will you not fear Allah?",
    "Do you call upon Ba'l and leave the best of creators -",
    "Allah, your Lord and the Lord of your first forefathers?\"",
    "And they denied him, so indeed, they will be brought [for punishment],",
    "Except the chosen servants of Allah.",
    "And We left for him [favorable mention] among later generations:",
    "\"Peace upon Elias.\"",
    "Indeed, We thus reward the doers of good.",
    "Indeed, he was of Our believing servants.",
    "And indeed, Lot was among the messengers.",
    "[So mention] when We saved him and his family, all,",
    "Except his wife among those who remained [with the evildoers].",
    "Then We destroyed the others.",
    "And indeed, you pass by them in the morning",
    "And at night. Then will you not use reason?",
    "And indeed, Jonah was among the messengers.",
    "[Mention] when he ran away to the laden ship.",
    "And he drew lots and was among the losers.",
    "Then the fish swallowed him, while he was blameworthy.",
    "And had he not been of those who exalt Allah,",
    "He would have remained inside its belly until the Day they are resurrected.",
    "But We threw him onto the open shore while he was ill.",
    "And We caused to grow over him a gourd vine.",
    "And We sent him to [his people of] a hundred thousand or more.",
    "And they believed, so We gave them enjoyment [of life] for a time.",
    "So inquire of them, [O Muhammad], \"Does your Lord have daughters while they have sons?",
    "Or did We create the angels as females while they were witnesses?\"",
    "Unquestionably, it is out of their [invented] falsehood that they say,",
    "\"Allah has begotten,\" and indeed, they are liars.",
    "Has He chosen daughters over sons?",
    "What is [wrong] with you? How do you make judgement?",
    "Then will you not be reminded?",
    "Or do you have a clear authority?",
    "Then produce your scripture, if you should be truthful.",
    "And they have claimed between Him and the jinn a lineage, but the jinn have already known that they [who made such claims] will be brought to [punishment].",
    "Exalted is Allah above what they describe,",
    "Except the chosen servants of Allah [who do not share in that sin].",
    "So indeed, you [disbelievers] and whatever you worship,",
    "You cannot tempt [anyone] away from Him",
    "Except he who is to [enter and] burn in the Hellfire.",
    "[The angels say], \"There is not among us any except that he has a known position.",
    "And indeed, we are those who line up [for prayer].",
    "And indeed, we are those who exalt Allah.\"",
    "And indeed, the disbelievers used to say,",
    "\"If we had a message from [those of] the former peoples,",
    "We would have been the chosen servants of Allah.\"",
    "But they disbelieved in it, so they are going to know.",
    "And Our word has already preceded for Our servants, the messengers,",
    "[That] indeed, they would be those given victory",
    "And [that] indeed, Our soldiers will be those who overcome.",
    "So, [O Muhammad], leave them for a time.",
    "And see [what will befall] them, for they are going to see.",
    "Then for Our punishment are they impatient?",
    "But when it descends in their territory, then evil is the morning of those who were warned.",
    "And leave them for a time.",
    "And see, for they are going to see.",
    "Exalted is your Lord, the Lord of might, above what they describe.",
    "And peace upon the messengers.",
    "And praise to Allah, Lord of the worlds.",
    ""};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_as__saffat);
        recyclerView = (RecyclerView) findViewById(R.id.recycler_view_as_saffat);
        adapter = new Al_Fatihah_Adapter(verses, arabic_verses, sahih_international, english_verses);
        layoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize (true);
        recyclerView.setAdapter (adapter);
        AdView mAdView = (AdView) findViewById(R.id.adView);
        AdRequest adRequest = new AdRequest.Builder().build();
        mAdView.loadAd(adRequest);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(R.menu.play_arrow_menu, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        Toast.makeText(getApplicationContext(), "You need to download the premium version of this app: \"Learn To Read The Quran Premium\" to listen to the audio", Toast.LENGTH_LONG).show();
        return super.onOptionsItemSelected(item);
    }
}
