package com.tumblr.albandaci.learntoreadthequran.Surahs;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.widget.Toast;

import com.tumblr.albandaci.learntoreadthequran.Adapter.Al_Fatihah_Adapter;
import com.tumblr.albandaci.learntoreadthequran.R;

public class Ash_Shuara extends AppCompatActivity {

    private RecyclerView recyclerView;
    private RecyclerView.Adapter adapter;
    private RecyclerView.LayoutManager layoutManager;

    String [] verses = {"26:1", "26:2", "26:3", "26:4", "26:5", "26:6", "26:7", "26:8", "26:9", "26:10", "26:11", "26:12", "26:13", "26:14", "26:15", "26:16",
            "26:17", "26:18", "26:19", "26:20", "26:21", "26:22", "26:23", "26:24", "26:25", "26:26", "26:27", "26:28", "26:29", "26:30", "26:31", "26:32",
            "26:33", "26:34", "26:35", "26:36", "26:37", "26:38", "26:39", "26:40", "26:41", "26:42", "26:43", "26:44", "26:45", "26:46", "26:47", "26:48",
            "26:49", "26:50", "26:51", "26:52", "26:53", "26:54", "26:55", "26:56", "26:57", "26:58", "26:59", "26:60", "26:61", "26:62", "26:63", "26:64",
            "26:65", "26:66", "26:67", "26:68", "26:69", "26:70", "26:71", "26:72", "26:73", "26:74", "26:75", "26:76", "26:77", "26:78", "26:79", "26:80",
            "26:81", "26:82", "26:83", "26:84", "26:85", "26:86", "26:87", "26:88", "26:89", "26:90", "26:91", "26:92", "26:93", "26:94", "26:95", "26:96",
            "26:97", "26:98", "26:99", "26:100", "26:101", "26:102", "26:103", "26:104", "26:105", "26:106", "26:107", "26:108", "26:109", "26:110", "26:111", "26:112",
            "26:113", "26:114", "26:115", "26:116", "26:117", "26:118", "26:119", "26:120", "26:121", "26:122", "26:123", "26:124", "26:125", "26:126", "26:127", "26:128",
            "26:129", "26:130", "26:131", "26:132", "26:133", "26:134", "26:135", "26:136", "26:137", "26:138", "26:139", "26:140", "26:141", "26:142", "26:143", "26:144",
            "26:145", "26:146", "26:147", "26:148", "26:149", "26:150", "26:151", "26:152", "26:153", "26:154", "26:155", "26:156", "26:157", "26:158", "26:159", "26:160",
            "26:161", "26:162", "26:163", "26:164", "26:165", "26:166", "26:167", "26:168", "26:169", "26:170", "26:171", "26:172", "26:173", "26:174", "26:175", "26:176",
            "26:177", "26:178", "26:179", "26:180", "26:181", "26:182", "26:183", "26:184", "26:185", "26:186", "26:187", "26:188", "26:189", "26:190", "26:191", "26:192",
            "26:193", "26:194", "26:195", "26:196", "26:197", "26:198", "26:199", "26:200", "26:201", "26:202", "26:203", "26:204", "26:205", "26:206", "26:207", "26:208",
            "26:209", "26:210", "26:211", "26:212", "26:213", "26:214", "26:215", "26:216", "26:217", "26:218", "26:219", "26:220", "26:221", "26:222", "26:223", "26:224",
            "26:225", "26:226", "26:227"};

    String [] arabic_verses = {"طسم",
    "تِلْكَ آيَاتُ الْكِتَابِ الْمُبِينِ",
    "لَعَلَّكَ بَاخِعٌ نَّفْسَكَ أَلَّا يَكُونُوا مُؤْمِنِينَ",
    "إِن نَّشَأْ نُنَزِّلْ عَلَيْهِم مِّنَ السَّمَاءِ آيَةً فَظَلَّتْ أَعْنَاقُهُمْ لَهَا خَاضِعِينَ",
    "وَمَا يَأْتِيهِم مِّن ذِكْرٍ مِّنَ الرَّحْمَٰنِ مُحْدَثٍ إِلَّا كَانُوا عَنْهُ مُعْرِضِينَ",
    "فَقَدْ كَذَّبُوا فَسَيَأْتِيهِمْ أَنبَاءُ مَا كَانُوا بِهِ يَسْتَهْزِئُونَ",
    "أَوَلَمْ يَرَوْا إِلَى الْأَرْضِ كَمْ أَنبَتْنَا فِيهَا مِن كُلِّ زَوْجٍ كَرِيمٍ",
    "إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "وَإِذْ نَادَىٰ رَبُّكَ مُوسَىٰ أَنِ ائْتِ الْقَوْمَ الظَّالِمِينَ",
    "قَوْمَ فِرْعَوْنَ ۚ أَلَا يَتَّقُونَ",
    "قَالَ رَبِّ إِنِّي أَخَافُ أَن يُكَذِّبُونِ",
    "وَيَضِيقُ صَدْرِي وَلَا يَنطَلِقُ لِسَانِي فَأَرْسِلْ إِلَىٰ هَارُونَ",
    "وَلَهُمْ عَلَيَّ ذَنبٌ فَأَخَافُ أَن يَقْتُلُونِ",
    "قَالَ كَلَّا ۖ فَاذْهَبَا بِآيَاتِنَا ۖ إِنَّا مَعَكُم مُّسْتَمِعُونَ",
    "فَأْتِيَا فِرْعَوْنَ فَقُولَا إِنَّا رَسُولُ رَبِّ الْعَالَمِينَ",
    "أَنْ أَرْسِلْ مَعَنَا بَنِي إِسْرَائِيلَ",
    "قَالَ أَلَمْ نُرَبِّكَ فِينَا وَلِيدًا وَلَبِثْتَ فِينَا مِنْ عُمُرِكَ سِنِينَ",
    "وَفَعَلْتَ فَعْلَتَكَ الَّتِي فَعَلْتَ وَأَنتَ مِنَ الْكَافِرِينَ",
    "قَالَ فَعَلْتُهَا إِذًا وَأَنَا مِنَ الضَّالِّينَ",
    "فَفَرَرْتُ مِنكُمْ لَمَّا خِفْتُكُمْ فَوَهَبَ لِي رَبِّي حُكْمًا وَجَعَلَنِي مِنَ الْمُرْسَلِينَ",
    "وَتِلْكَ نِعْمَةٌ تَمُنُّهَا عَلَيَّ أَنْ عَبَّدتَّ بَنِي إِسْرَائِيلَ",
    "قَالَ فِرْعَوْنُ وَمَا رَبُّ الْعَالَمِينَ",
    "قَالَ رَبُّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا ۖ إِن كُنتُم مُّوقِنِينَ",
    "قَالَ لِمَنْ حَوْلَهُ أَلَا تَسْتَمِعُونَ",
    "قَالَ رَبُّكُمْ وَرَبُّ آبَائِكُمُ الْأَوَّلِينَ",
    "قَالَ إِنَّ رَسُولَكُمُ الَّذِي أُرْسِلَ إِلَيْكُمْ لَمَجْنُونٌ",
    "قَالَ رَبُّ الْمَشْرِقِ وَالْمَغْرِبِ وَمَا بَيْنَهُمَا ۖ إِن كُنتُمْ تَعْقِلُونَ",
    "قَالَ لَئِنِ اتَّخَذْتَ إِلَٰهًا غَيْرِي لَأَجْعَلَنَّكَ مِنَ الْمَسْجُونِينَ",
    "قَالَ أَوَلَوْ جِئْتُكَ بِشَيْءٍ مُّبِينٍ",
    "قَالَ فَأْتِ بِهِ إِن كُنتَ مِنَ الصَّادِقِينَ",
    "فَأَلْقَىٰ عَصَاهُ فَإِذَا هِيَ ثُعْبَانٌ مُّبِينٌ",
    "وَنَزَعَ يَدَهُ فَإِذَا هِيَ بَيْضَاءُ لِلنَّاظِرِينَ",
    "قَالَ لِلْمَلَإِ حَوْلَهُ إِنَّ هَٰذَا لَسَاحِرٌ عَلِيمٌ",
    "يُرِيدُ أَن يُخْرِجَكُم مِّنْ أَرْضِكُم بِسِحْرِهِ فَمَاذَا تَأْمُرُونَ",
    "قَالُوا أَرْجِهْ وَأَخَاهُ وَابْعَثْ فِي الْمَدَائِنِ حَاشِرِينَ",
    "يَأْتُوكَ بِكُلِّ سَحَّارٍ عَلِيمٍ",
    "فَجُمِعَ السَّحَرَةُ لِمِيقَاتِ يَوْمٍ مَّعْلُومٍ",
    "وَقِيلَ لِلنَّاسِ هَلْ أَنتُم مُّجْتَمِعُونَ",
    "لَعَلَّنَا نَتَّبِعُ السَّحَرَةَ إِن كَانُوا هُمُ الْغَالِبِينَ",
    "فَلَمَّا جَاءَ السَّحَرَةُ قَالُوا لِفِرْعَوْنَ أَئِنَّ لَنَا لَأَجْرًا إِن كُنَّا نَحْنُ الْغَالِبِينَ",
    "قَالَ نَعَمْ وَإِنَّكُمْ إِذًا لَّمِنَ الْمُقَرَّبِينَ",
    "قَالَ لَهُم مُّوسَىٰ أَلْقُوا مَا أَنتُم مُّلْقُونَ",
    "فَأَلْقَوْا حِبَالَهُمْ وَعِصِيَّهُمْ وَقَالُوا بِعِزَّةِ فِرْعَوْنَ إِنَّا لَنَحْنُ الْغَالِبُونَ",
    "فَأَلْقَىٰ مُوسَىٰ عَصَاهُ فَإِذَا هِيَ تَلْقَفُ مَا يَأْفِكُونَ",
    "فَأُلْقِيَ السَّحَرَةُ سَاجِدِينَ",
    "قَالُوا آمَنَّا بِرَبِّ الْعَالَمِينَ",
    "رَبِّ مُوسَىٰ وَهَارُونَ",
    "قَالَ آمَنتُمْ لَهُ قَبْلَ أَنْ آذَنَ لَكُمْ ۖ إِنَّهُ لَكَبِيرُكُمُ الَّذِي عَلَّمَكُمُ السِّحْرَ فَلَسَوْفَ تَعْلَمُونَ ۚ لَأُقَطِّعَنَّ أَيْدِيَكُمْ وَأَرْجُلَكُم مِّنْ خِلَافٍ وَلَأُصَلِّبَنَّكُمْ أَجْمَعِينَ",
    "قَالُوا لَا ضَيْرَ ۖ إِنَّا إِلَىٰ رَبِّنَا مُنقَلِبُونَ",
    "إِنَّا نَطْمَعُ أَن يَغْفِرَ لَنَا رَبُّنَا خَطَايَانَا أَن كُنَّا أَوَّلَ الْمُؤْمِنِينَ",
    "وَأَوْحَيْنَا إِلَىٰ مُوسَىٰ أَنْ أَسْرِ بِعِبَادِي إِنَّكُم مُّتَّبَعُونَ",
    "فَأَرْسَلَ فِرْعَوْنُ فِي الْمَدَائِنِ حَاشِرِينَ",
    "إِنَّ هَٰؤُلَاءِ لَشِرْذِمَةٌ قَلِيلُونَ",
    "وَإِنَّهُمْ لَنَا لَغَائِظُونَ",
    "وَإِنَّا لَجَمِيعٌ حَاذِرُونَ",
    "فَأَخْرَجْنَاهُم مِّن جَنَّاتٍ وَعُيُونٍ",
    "وَكُنُوزٍ وَمَقَامٍ كَرِيمٍ",
    "كَذَٰلِكَ وَأَوْرَثْنَاهَا بَنِي إِسْرَائِيلَ",
    "فَأَتْبَعُوهُم مُّشْرِقِينَ",
    "فَلَمَّا تَرَاءَى الْجَمْعَانِ قَالَ أَصْحَابُ مُوسَىٰ إِنَّا لَمُدْرَكُونَ",
    "قَالَ كَلَّا ۖ إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ",
    "فَأَوْحَيْنَا إِلَىٰ مُوسَىٰ أَنِ اضْرِب بِّعَصَاكَ الْبَحْرَ ۖ فَانفَلَقَ فَكَانَ كُلُّ فِرْقٍ كَالطَّوْدِ الْعَظِيمِ",
    "وَأَزْلَفْنَا ثَمَّ الْآخَرِينَ",
    "وَأَنجَيْنَا مُوسَىٰ وَمَن مَّعَهُ أَجْمَعِينَ",
    "ثُمَّ أَغْرَقْنَا الْآخَرِينَ",
    "إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "وَاتْلُ عَلَيْهِمْ نَبَأَ إِبْرَاهِيمَ",
    "إِذْ قَالَ لِأَبِيهِ وَقَوْمِهِ مَا تَعْبُدُونَ",
    "قَالُوا نَعْبُدُ أَصْنَامًا فَنَظَلُّ لَهَا عَاكِفِينَ",
    "قَالَ هَلْ يَسْمَعُونَكُمْ إِذْ تَدْعُونَ",
    "أَوْ يَنفَعُونَكُمْ أَوْ يَضُرُّونَ",
    "قَالُوا بَلْ وَجَدْنَا آبَاءَنَا كَذَٰلِكَ يَفْعَلُونَ",
    "قَالَ أَفَرَأَيْتُم مَّا كُنتُمْ تَعْبُدُونَ",
    "أَنتُمْ وَآبَاؤُكُمُ الْأَقْدَمُونَ",
    "فَإِنَّهُمْ عَدُوٌّ لِّي إِلَّا رَبَّ الْعَالَمِينَ",
    "الَّذِي خَلَقَنِي فَهُوَ يَهْدِينِ",
    "وَالَّذِي هُوَ يُطْعِمُنِي وَيَسْقِينِ",
    "وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ",
    "وَالَّذِي يُمِيتُنِي ثُمَّ يُحْيِينِ",
    "وَالَّذِي أَطْمَعُ أَن يَغْفِرَ لِي خَطِيئَتِي يَوْمَ الدِّينِ",
    "رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ",
    "وَاجْعَل لِّي لِسَانَ صِدْقٍ فِي الْآخِرِينَ",
    "وَاجْعَلْنِي مِن وَرَثَةِ جَنَّةِ النَّعِيمِ",
    "وَاغْفِرْ لِأَبِي إِنَّهُ كَانَ مِنَ الضَّالِّينَ",
    "وَلَا تُخْزِنِي يَوْمَ يُبْعَثُونَ",
    "يَوْمَ لَا يَنفَعُ مَالٌ وَلَا بَنُونَ",
    "إِلَّا مَنْ أَتَى اللَّهَ بِقَلْبٍ سَلِيمٍ",
    "وَأُزْلِفَتِ الْجَنَّةُ لِلْمُتَّقِينَ",
    "وَبُرِّزَتِ الْجَحِيمُ لِلْغَاوِينَ",
    "وَقِيلَ لَهُمْ أَيْنَ مَا كُنتُمْ تَعْبُدُونَ",
    "مِن دُونِ اللَّهِ هَلْ يَنصُرُونَكُمْ أَوْ يَنتَصِرُونَ",
    "فَكُبْكِبُوا فِيهَا هُمْ وَالْغَاوُونَ",
    "وَجُنُودُ إِبْلِيسَ أَجْمَعُونَ",
    "قَالُوا وَهُمْ فِيهَا يَخْتَصِمُونَ",
    "تَاللَّهِ إِن كُنَّا لَفِي ضَلَالٍ مُّبِينٍ",
    "إِذْ نُسَوِّيكُم بِرَبِّ الْعَالَمِينَ",
    "وَمَا أَضَلَّنَا إِلَّا الْمُجْرِمُونَ",
    "فَمَا لَنَا مِن شَافِعِينَ",
    "وَلَا صَدِيقٍ حَمِيمٍ",
    "فَلَوْ أَنَّ لَنَا كَرَّةً فَنَكُونَ مِنَ الْمُؤْمِنِينَ",
    "إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "كَذَّبَتْ قَوْمُ نُوحٍ الْمُرْسَلِينَ",
    "إِذْ قَالَ لَهُمْ أَخُوهُمْ نُوحٌ أَلَا تَتَّقُونَ",
    "إِنِّي لَكُمْ رَسُولٌ أَمِينٌ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ ۖ إِنْ أَجْرِيَ إِلَّا عَلَىٰ رَبِّ الْعَالَمِينَ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "قَالُوا أَنُؤْمِنُ لَكَ وَاتَّبَعَكَ الْأَرْذَلُونَ",
    "قَالَ وَمَا عِلْمِي بِمَا كَانُوا يَعْمَلُونَ",
    "إِنْ حِسَابُهُمْ إِلَّا عَلَىٰ رَبِّي ۖ لَوْ تَشْعُرُونَ",
    "وَمَا أَنَا بِطَارِدِ الْمُؤْمِنِينَ",
    "إِنْ أَنَا إِلَّا نَذِيرٌ مُّبِينٌ",
    "قَالُوا لَئِن لَّمْ تَنتَهِ يَا نُوحُ لَتَكُونَنَّ مِنَ الْمَرْجُومِينَ",
    "قَالَ رَبِّ إِنَّ قَوْمِي كَذَّبُونِ",
    "فَافْتَحْ بَيْنِي وَبَيْنَهُمْ فَتْحًا وَنَجِّنِي وَمَن مَّعِيَ مِنَ الْمُؤْمِنِينَ",
    "فَأَنجَيْنَاهُ وَمَن مَّعَهُ فِي الْفُلْكِ الْمَشْحُونِ",
    "ثُمَّ أَغْرَقْنَا بَعْدُ الْبَاقِينَ",
    "إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "كَذَّبَتْ عَادٌ الْمُرْسَلِينَ",
    "إِذْ قَالَ لَهُمْ أَخُوهُمْ هُودٌ أَلَا تَتَّقُونَ",
    "إِنِّي لَكُمْ رَسُولٌ أَمِينٌ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ ۖ إِنْ أَجْرِيَ إِلَّا عَلَىٰ رَبِّ الْعَالَمِينَ",
    "أَتَبْنُونَ بِكُلِّ رِيعٍ آيَةً تَعْبَثُونَ",
    "وَتَتَّخِذُونَ مَصَانِعَ لَعَلَّكُمْ تَخْلُدُونَ",
    "وَإِذَا بَطَشْتُم بَطَشْتُمْ جَبَّارِينَ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "وَاتَّقُوا الَّذِي أَمَدَّكُم بِمَا تَعْلَمُونَ",
    "أَمَدَّكُم بِأَنْعَامٍ وَبَنِينَ",
    "وَجَنَّاتٍ وَعُيُونٍ",
    "إِنِّي أَخَافُ عَلَيْكُمْ عَذَابَ يَوْمٍ عَظِيمٍ",
    "قَالُوا سَوَاءٌ عَلَيْنَا أَوَعَظْتَ أَمْ لَمْ تَكُن مِّنَ الْوَاعِظِينَ",
    "إِنْ هَٰذَا إِلَّا خُلُقُ الْأَوَّلِينَ",
    "وَمَا نَحْنُ بِمُعَذَّبِينَ",
    "فَكَذَّبُوهُ فَأَهْلَكْنَاهُمْ ۗ إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "كَذَّبَتْ ثَمُودُ الْمُرْسَلِينَ",
    "إِذْ قَالَ لَهُمْ أَخُوهُمْ صَالِحٌ أَلَا تَتَّقُونَ",
    "إِنِّي لَكُمْ رَسُولٌ أَمِينٌ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ ۖ إِنْ أَجْرِيَ إِلَّا عَلَىٰ رَبِّ الْعَالَمِينَ",
    "أَتُتْرَكُونَ فِي مَا هَاهُنَا آمِنِينَ",
    "فِي جَنَّاتٍ وَعُيُونٍ",
    "وَزُرُوعٍ وَنَخْلٍ طَلْعُهَا هَضِيمٌ",
    "وَتَنْحِتُونَ مِنَ الْجِبَالِ بُيُوتًا فَارِهِينَ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "وَلَا تُطِيعُوا أَمْرَ الْمُسْرِفِينَ",
    "الَّذِينَ يُفْسِدُونَ فِي الْأَرْضِ وَلَا يُصْلِحُونَ",
    "قَالُوا إِنَّمَا أَنتَ مِنَ الْمُسَحَّرِينَ",
    "مَا أَنتَ إِلَّا بَشَرٌ مِّثْلُنَا فَأْتِ بِآيَةٍ إِن كُنتَ مِنَ الصَّادِقِينَ",
    "قَالَ هَٰذِهِ نَاقَةٌ لَّهَا شِرْبٌ وَلَكُمْ شِرْبُ يَوْمٍ مَّعْلُومٍ",
    "وَلَا تَمَسُّوهَا بِسُوءٍ فَيَأْخُذَكُمْ عَذَابُ يَوْمٍ عَظِيمٍ",
    "فَعَقَرُوهَا فَأَصْبَحُوا نَادِمِينَ",
    "فَأَخَذَهُمُ الْعَذَابُ ۗ إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "كَذَّبَتْ قَوْمُ لُوطٍ الْمُرْسَلِينَ",
    "إِذْ قَالَ لَهُمْ أَخُوهُمْ لُوطٌ أَلَا تَتَّقُونَ",
    "إِنِّي لَكُمْ رَسُولٌ أَمِينٌ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ ۖ إِنْ أَجْرِيَ إِلَّا عَلَىٰ رَبِّ الْعَالَمِينَ",
    "أَتَأْتُونَ الذُّكْرَانَ مِنَ الْعَالَمِينَ",
    "وَتَذَرُونَ مَا خَلَقَ لَكُمْ رَبُّكُم مِّنْ أَزْوَاجِكُم ۚ بَلْ أَنتُمْ قَوْمٌ عَادُونَ",
    "قَالُوا لَئِن لَّمْ تَنتَهِ يَا لُوطُ لَتَكُونَنَّ مِنَ الْمُخْرَجِينَ",
    "قَالَ إِنِّي لِعَمَلِكُم مِّنَ الْقَالِينَ",
    "رَبِّ نَجِّنِي وَأَهْلِي مِمَّا يَعْمَلُونَ",
    "فَنَجَّيْنَاهُ وَأَهْلَهُ أَجْمَعِينَ",
    "إِلَّا عَجُوزًا فِي الْغَابِرِينَ",
    "ثُمَّ دَمَّرْنَا الْآخَرِينَ",
    "وَأَمْطَرْنَا عَلَيْهِم مَّطَرًا ۖ فَسَاءَ مَطَرُ الْمُنذَرِينَ",
    "إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "كَذَّبَ أَصْحَابُ الْأَيْكَةِ الْمُرْسَلِينَ",
    "إِذْ قَالَ لَهُمْ شُعَيْبٌ أَلَا تَتَّقُونَ",
    "إِنِّي لَكُمْ رَسُولٌ أَمِينٌ",
    "فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    "وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ ۖ إِنْ أَجْرِيَ إِلَّا عَلَىٰ رَبِّ الْعَالَمِينَ",
    "أَوْفُوا الْكَيْلَ وَلَا تَكُونُوا مِنَ الْمُخْسِرِينَ",
    "وَزِنُوا بِالْقِسْطَاسِ الْمُسْتَقِيمِ",
    "وَلَا تَبْخَسُوا النَّاسَ أَشْيَاءَهُمْ وَلَا تَعْثَوْا فِي الْأَرْضِ مُفْسِدِينَ",
    "وَاتَّقُوا الَّذِي خَلَقَكُمْ وَالْجِبِلَّةَ الْأَوَّلِينَ",
    "قَالُوا إِنَّمَا أَنتَ مِنَ الْمُسَحَّرِينَ",
    "وَمَا أَنتَ إِلَّا بَشَرٌ مِّثْلُنَا وَإِن نَّظُنُّكَ لَمِنَ الْكَاذِبِينَ",
    "فَأَسْقِطْ عَلَيْنَا كِسَفًا مِّنَ السَّمَاءِ إِن كُنتَ مِنَ الصَّادِقِينَ",
    "قَالَ رَبِّي أَعْلَمُ بِمَا تَعْمَلُونَ",
    "فَكَذَّبُوهُ فَأَخَذَهُمْ عَذَابُ يَوْمِ الظُّلَّةِ ۚ إِنَّهُ كَانَ عَذَابَ يَوْمٍ عَظِيمٍ",
    "إِنَّ فِي ذَٰلِكَ لَآيَةً ۖ وَمَا كَانَ أَكْثَرُهُم مُّؤْمِنِينَ",
    "وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ",
    "وَإِنَّهُ لَتَنزِيلُ رَبِّ الْعَالَمِينَ",
    "نَزَلَ بِهِ الرُّوحُ الْأَمِينُ",
    "عَلَىٰ قَلْبِكَ لِتَكُونَ مِنَ الْمُنذِرِينَ",
    "بِلِسَانٍ عَرَبِيٍّ مُّبِينٍ",
    "وَإِنَّهُ لَفِي زُبُرِ الْأَوَّلِينَ",
    "أَوَلَمْ يَكُن لَّهُمْ آيَةً أَن يَعْلَمَهُ عُلَمَاءُ بَنِي إِسْرَائِيلَ",
    "وَلَوْ نَزَّلْنَاهُ عَلَىٰ بَعْضِ الْأَعْجَمِينَ",
    "فَقَرَأَهُ عَلَيْهِم مَّا كَانُوا بِهِ مُؤْمِنِينَ",
    "كَذَٰلِكَ سَلَكْنَاهُ فِي قُلُوبِ الْمُجْرِمِينَ",
    "لَا يُؤْمِنُونَ بِهِ حَتَّىٰ يَرَوُا الْعَذَابَ الْأَلِيمَ",
    "فَيَأْتِيَهُم بَغْتَةً وَهُمْ لَا يَشْعُرُونَ",
    "فَيَقُولُوا هَلْ نَحْنُ مُنظَرُونَ",
    "أَفَبِعَذَابِنَا يَسْتَعْجِلُونَ",
    "أَفَرَأَيْتَ إِن مَّتَّعْنَاهُمْ سِنِينَ",
    "ثُمَّ جَاءَهُم مَّا كَانُوا يُوعَدُونَ",
    "مَا أَغْنَىٰ عَنْهُم مَّا كَانُوا يُمَتَّعُونَ",
    "وَمَا أَهْلَكْنَا مِن قَرْيَةٍ إِلَّا لَهَا مُنذِرُونَ",
    "ذِكْرَىٰ وَمَا كُنَّا ظَالِمِينَ",
    "وَمَا تَنَزَّلَتْ بِهِ الشَّيَاطِينُ",
    "وَمَا يَنبَغِي لَهُمْ وَمَا يَسْتَطِيعُونَ",
    "إِنَّهُمْ عَنِ السَّمْعِ لَمَعْزُولُونَ",
    "فَلَا تَدْعُ مَعَ اللَّهِ إِلَٰهًا آخَرَ فَتَكُونَ مِنَ الْمُعَذَّبِينَ",
    "وَأَنذِرْ عَشِيرَتَكَ الْأَقْرَبِينَ",
    "وَاخْفِضْ جَنَاحَكَ لِمَنِ اتَّبَعَكَ مِنَ الْمُؤْمِنِينَ",
    "فَإِنْ عَصَوْكَ فَقُلْ إِنِّي بَرِيءٌ مِّمَّا تَعْمَلُونَ",
    "وَتَوَكَّلْ عَلَى الْعَزِيزِ الرَّحِيمِ",
    "الَّذِي يَرَاكَ حِينَ تَقُومُ",
    "وَتَقَلُّبَكَ فِي السَّاجِدِينَ",
    "إِنَّهُ هُوَ السَّمِيعُ الْعَلِيمُ",
    "هَلْ أُنَبِّئُكُمْ عَلَىٰ مَن تَنَزَّلُ الشَّيَاطِينُ",
    "تَنَزَّلُ عَلَىٰ كُلِّ أَفَّاكٍ أَثِيمٍ",
    "يُلْقُونَ السَّمْعَ وَأَكْثَرُهُمْ كَاذِبُونَ",
    "وَالشُّعَرَاءُ يَتَّبِعُهُمُ الْغَاوُونَ",
    "أَلَمْ تَرَ أَنَّهُمْ فِي كُلِّ وَادٍ يَهِيمُونَ",
    "وَأَنَّهُمْ يَقُولُونَ مَا لَا يَفْعَلُونَ",
    "إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَذَكَرُوا اللَّهَ كَثِيرًا وَانتَصَرُوا مِن بَعْدِ مَا ظُلِمُوا ۗ وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنقَلَبٍ يَنقَلِبُونَ"};

    String [] sahih_international = {"Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International",
            "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International", "Sahih International"};

    String [] english_verses = {"Ta, Seen, Meem.",
    "These are the verses of the clear Book.",
    "Perhaps, [O Muhammad], you would kill yourself with grief that they will not be believers.",
    "If We willed, We could send down to them from the sky a sign for which their necks would remain humbled.",
    "And no revelation comes to them anew from the Most Merciful except that they turn away from it.",
    "For they have already denied, but there will come to them the news of that which they used to ridicule.",
    "Did they not look at the earth - how much We have produced therein from every noble kind?",
    "Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "And [mention] when your Lord called Moses, [saying], \"Go to the wrongdoing people -",
    "The people of Pharaoh. Will they not fear Allah?\"",
    "He said, \"My Lord, indeed I fear that they will deny me",
    "And that my breast will tighten and my tongue will not be fluent, so send for Aaron.",
    "And they have upon me a [claim due to] sin, so I fear that they will kill me.\"",
    "[Allah] said, \"No. Go both of you with Our signs; indeed, We are with you, listening.",
    "Go to Pharaoh and say, 'We are the messengers of the Lord of the worlds,",
    "[Commanded to say], \"Send with us the Children of Israel.\" ' \"",
    "[Pharaoh] said, \"Did we not raise you among us as a child, and you remained among us for years of your life?",
    "And [then] you did your deed which you did, and you were of the ungrateful.\"",
    "[Moses] said, \"I did it, then, while I was of those astray.",
    "So I fled from you when I feared you. Then my Lord granted me wisdom and prophethood and appointed me [as one] of the messengers.",
    "And is this a favor of which you remind me - that you have enslaved the Children of Israel?\"",
    "Said Pharaoh, \"And what is the Lord of the worlds?\"",
    "[Moses] said, \"The Lord of the heavens and earth and that between them, if you should be convinced.\"",
    "[Pharaoh] said to those around him, \"Do you not hear?\"",
    "[Moses] said, \"Your Lord and the Lord of your first forefathers.\"",
    "[Pharaoh] said, \"Indeed, your 'messenger' who has been sent to you is mad.\"",
    "[Moses] said, \"Lord of the east and the west and that between them, if you were to reason.\"",
    "[Pharaoh] said, \"If you take a god other than me, I will surely place you among those imprisoned.\"",
    "[Moses] said, \"Even if I brought you proof manifest?\"",
    "[Pharaoh] said, \"Then bring it, if you should be of the truthful.\"",
    "So [Moses] threw his staff, and suddenly it was a serpent manifest.",
    "And he drew out his hand; thereupon it was white for the observers.",
    "[Pharaoh] said to the eminent ones around him, \"Indeed, this is a learned magician.",
    "He wants to drive you out of your land by his magic, so what do you advise?\"",
    "They said, \"Postpone [the matter of] him and his brother and send among the cities gatherers",
    "Who will bring you every learned, skilled magician.\"",
    "So the magicians were assembled for the appointment of a well-known day.",
    "And it was said to the people, \"Will you congregate",
    "That we might follow the magicians if they are the predominant?\"",
    "And when the magicians arrived, they said to Pharaoh, \"Is there indeed for us a reward if we are the predominant?\"",
    "He said, \"Yes, and indeed, you will then be of those near [to me].\"",
    "Moses said to them, \"Throw whatever you will throw.\"",
    "So they threw their ropes and their staffs and said, \"By the might of Pharaoh, indeed it is we who are predominant.\"",
    "Then Moses threw his staff, and at once it devoured what they falsified.",
    "So the magicians fell down in prostration [to Allah].",
    "They said, \"We have believed in the Lord of the worlds,",
    "The Lord of Moses and Aaron.\"",
    "[Pharaoh] said, \"You believed Moses before I gave you permission. Indeed, he is your leader who has taught you magic, but you are going to know. I will surely cut off your hands and your feet on opposite sides, and I will surely crucify you all.\"",
    "They said, \"No harm. Indeed, to our Lord we will return.",
    "Indeed, we aspire that our Lord will forgive us our sins because we were the first of the believers.\"",
    "And We inspired to Moses, \"Travel by night with My servants; indeed, you will be pursued.\"",
    "Then Pharaoh sent among the cities gatherers",
    "[And said], \"Indeed, those are but a small band,",
    "And indeed, they are enraging us,",
    "And indeed, we are a cautious society... \"",
    "So We removed them from gardens and springs",
    "And treasures and honorable station -",
    "Thus. And We caused to inherit it the Children of Israel.",
    "So they pursued them at sunrise.",
    "And when the two companies saw one another, the companions of Moses said, \"Indeed, we are to be overtaken!\"",
    "[Moses] said, \"No! Indeed, with me is my Lord; He will guide me.\"",
    "Then We inspired to Moses, \"Strike with your staff the sea,\" and it parted, and each portion was like a great towering mountain.",
    "And We advanced thereto the pursuers.",
    "And We saved Moses and those with him, all together.",
    "Then We drowned the others.",
    "Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "And recite to them the news of Abraham,",
    "When he said to his father and his people, \"What do you worship?\"",
    "They said, \"We worship idols and remain to them devoted.\"",
    "He said, \"Do they hear you when you supplicate?",
    "Or do they benefit you, or do they harm?\"",
    "They said, \"But we found our fathers doing thus.\"",
    "He said, \"Then do you see what you have been worshipping,",
    "You and your ancient forefathers?",
    "Indeed, they are enemies to me, except the Lord of the worlds,",
    "Who created me, and He [it is who] guides me.",
    "And it is He who feeds me and gives me drink.",
    "And when I am ill, it is He who cures me",
    "And who will cause me to die and then bring me to life",
    "And who I aspire that He will forgive me my sin on the Day of Recompense.\"",
    "[And he said], \"My Lord, grant me authority and join me with the righteous.",
    "And grant me a reputation of honor among later generations.",
    "And place me among the inheritors of the Garden of Pleasure.",
    "And forgive my father. Indeed, he has been of those astray.",
    "And do not disgrace me on the Day they are [all] resurrected -",
    "The Day when there will not benefit [anyone] wealth or children",
    "But only one who comes to Allah with a sound heart.\"",
    "And Paradise will be brought near [that Day] to the righteous.",
    "And Hellfire will be brought forth for the deviators,",
    "And it will be said to them, \"Where are those you used to worship",
    "Other than Allah? Can they help you or help themselves?\"",
    "So they will be overturned into Hellfire, they and the deviators",
    "And the soldiers of Iblees, all together.",
    "They will say while they dispute therein,",
    "\"By Allah, we were indeed in manifest error",
    "When we equated you with the Lord of the worlds.",
    "And no one misguided us except the criminals.",
    "So now we have no intercessors",
    "And not a devoted friend.",
    "Then if we only had a return [to the world] and could be of the believers... \"",
    "Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "The people of Noah denied the messengers",
    "When their brother Noah said to them, \"Will you not fear Allah?",
    "Indeed, I am to you a trustworthy messenger.",
    "So fear Allah and obey me.",
    "And I do not ask you for it any payment. My payment is only from the Lord of the worlds.",
    "So fear Allah and obey me.\"",
    "They said, \"Should we believe you while you are followed by the lowest [class of people]?\"",
    "He said, \"And what is my knowledge of what they used to do?",
    "Their account is only upon my Lord, if you [could] perceive.",
    "And I am not one to drive away the believers.",
    "I am only a clear warner.\"",
    "They said, \"If you do not desist, O Noah, you will surely be of those who are stoned.\"",
    "He said, \"My Lord, indeed my people have denied me.",
    "Then judge between me and them with decisive judgement and save me and those with me of the believers.\"",
    "So We saved him and those with him in the laden ship.",
    "Then We drowned thereafter the remaining ones.",
    "Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "'Aad denied the messengers",
    "When their brother Hud said to them, \"Will you not fear Allah?",
    "Indeed, I am to you a trustworthy messenger.",
    "So fear Allah and obey me.",
    "And I do not ask you for it any payment. My payment is only from the Lord of the worlds.",
    "Do you construct on every elevation a sign, amusing yourselves,",
    "And take for yourselves palaces and fortresses that you might abide eternally?",
    "And when you strike, you strike as tyrants.",
    "So fear Allah and obey me.",
    "And fear He who provided you with that which you know,",
    "Provided you with grazing livestock and children",
    "And gardens and springs.",
    "Indeed, I fear for you the punishment of a terrible day.\"",
    "They said, \"It is all the same to us whether you advise or are not of the advisors.",
    "This is not but the custom of the former peoples,",
    "And we are not to be punished.\"",
    "And they denied him, so We destroyed them. Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "Thamud denied the messengers",
    "When their brother Salih said to them, \"Will you not fear Allah?",
    "Indeed, I am to you a trustworthy messenger.",
    "So fear Allah and obey me.",
    "And I do not ask you for it any payment. My payment is only from the Lord of the worlds.",
    "Will you be left in what is here, secure [from death],",
    "Within gardens and springs",
    "And fields of crops and palm trees with softened fruit?",
    "And you carve out of the mountains, homes, with skill.",
    "So fear Allah and obey me.",
    "And do not obey the order of the transgressors,",
    "Who cause corruption in the land and do not amend.\"",
    "They said, \"You are only of those affected by magic.",
    "You are but a man like ourselves, so bring a sign, if you should be of the truthful.\"",
    "He said, \"This is a she-camel. For her is a [time of] drink, and for you is a [time of] drink, [each] on a known day.",
    "And do not touch her with harm, lest you be seized by the punishment of a terrible day.\"",
    "But they hamstrung her and so became regretful.",
    "And the punishment seized them. Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "The people of Lot denied the messengers",
    "When their brother Lot said to them, \"Will you not fear Allah?",
    "Indeed, I am to you a trustworthy messenger.",
    "So fear Allah and obey me.",
    "And I do not ask you for it any payment. My payment is only from the Lord of the worlds.",
    "Do you approach males among the worlds",
    "And leave what your Lord has created for you as mates? But you are a people transgressing.\"",
    "They said, \"If you do not desist, O Lot, you will surely be of those evicted.\"",
    "He said, \"Indeed, I am, toward your deed, of those who detest [it].",
    "My Lord, save me and my family from [the consequence of] what they do.\"",
    "So We saved him and his family, all,",
    "Except an old woman among those who remained behind.",
    "Then We destroyed the others.",
    "And We rained upon them a rain [of stones], and evil was the rain of those who were warned.",
    "Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "The companions of the thicket denied the messengers",
    "When Shu'ayb said to them, \"Will you not fear Allah?",
    "Indeed, I am to you a trustworthy messenger.",
    "So fear Allah and obey me.",
    "And I do not ask you for it any payment. My payment is only from the Lord of the worlds.",
    "Give full measure and do not be of those who cause loss.",
    "And weigh with an even balance.",
    "And do not deprive people of their due and do not commit abuse on earth, spreading corruption.",
    "And fear He who created you and the former creation.\"",
    "They said, \"You are only of those affected by magic.",
    "You are but a man like ourselves, and indeed, we think you are among the liars.",
    "So cause to fall upon us fragments of the sky, if you should be of the truthful.\"",
    "He said, \"My Lord is most knowing of what you do.\"",
    "And they denied him, so the punishment of the day of the black cloud seized them. Indeed, it was the punishment of a terrible day.",
    "Indeed in that is a sign, but most of them were not to be believers.",
    "And indeed, your Lord - He is the Exalted in Might, the Merciful.",
    "And indeed, the Qur'an is the revelation of the Lord of the worlds.",
    "The Trustworthy Spirit has brought it down",
    "Upon your heart, [O Muhammad] - that you may be of the warners -",
    "In a clear Arabic language.",
    "And indeed, it is [mentioned] in the scriptures of former peoples.",
    "And has it not been a sign to them that it is recognized by the scholars of the Children of Israel?",
    "And even if We had revealed it to one among the foreigners",
    "And he had recited it to them [perfectly], they would [still] not have been believers in it.",
    "Thus have We inserted disbelief into the hearts of the criminals.",
    "They will not believe in it until they see the painful punishment.",
    "And it will come to them suddenly while they perceive [it] not.",
    "And they will say, \"May we be reprieved?\"",
    "So for Our punishment are they impatient?",
    "Then have you considered if We gave them enjoyment for years",
    "And then there came to them that which they were promised?",
    "They would not be availed by the enjoyment with which they were provided.",
    "And We did not destroy any city except that it had warners",
    "As a reminder; and never have We been unjust.",
    "And the devils have not brought the revelation down.",
    "It is not allowable for them, nor would they be able.",
    "Indeed they, from [its] hearing, are removed.",
    "So do not invoke with Allah another deity and [thus] be among the punished.",
    "And warn, [O Muhammad], your closest kindred.",
    "And lower your wing to those who follow you of the believers.",
    "And if they disobey you, then say, \"Indeed, I am disassociated from what you are doing.\"",
    "And rely upon the Exalted in Might, the Merciful,",
    "Who sees you when you arise",
    "And your movement among those who prostrate.",
    "Indeed, He is the Hearing, the Knowing.",
    "Shall I inform you upon whom the devils descend?",
    "They descend upon every sinful liar.",
    "They pass on what is heard, and most of them are liars.",
    "And the poets - [only] the deviators follow them;",
    "Do you not see that in every valley they roam",
    "And that they say what they do not do? -",
    "Except those [poets] who believe and do righteous deeds and remember Allah often and defend [the Muslims] after they were wronged. And those who have wronged are going to know to what [kind of] return they will be returned."};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ash__shuara);
        recyclerView = (RecyclerView) findViewById(R.id.recycler_view_ash_shuara);
        adapter = new Al_Fatihah_Adapter(verses, arabic_verses, sahih_international, english_verses);
        layoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize (true);
        recyclerView.setAdapter (adapter);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(R.menu.play_arrow_menu, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        Toast.makeText(getApplicationContext(), "You need to download the premium version of this app: \"Learn To Read The Quran Premium\" to listen to the audio", Toast.LENGTH_LONG).show();
        return super.onOptionsItemSelected(item);
    }
}
